### ISSUE TITLE
Re-add support for older docutils versions

### ISSUE THREAD

**Issue by AlexanderLanin** [PyCQA/doc8#109]
doc8 currently requires docutils `>=0.19` which is the latest version that exists at the moment. Is this really a hard requirement or was it set by accident within [PR-103](https://github.com/PyCQA/doc8/pull/103/files#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52)?
I do not know if it is reasonable to require e.g. `>=0.18.1` instead.
 
Background: The trouble is that many different modules require specific docutils versions. doc8 is extremely strict in requiring the latest one, which is not yet supported by all the other modules.

**Comment by ssbarnea** [comment]
To be fair, this will not happen. The project does not have enough maintainers to afford extra testing with multiple versions. If that causes conflicts for you, use an old version, or use it as a pre-commit hook. We even had to ceil the top version because we did not had the time to add support for newer ones.
